@host = http://localhost:5055

### Criar tarefa
POST {{host}}/api/tasks
Content-Type: application/json

{
  "title": "Estudar para entrevista",
  "description": "Revisar Clean Architecture",
  "status": "Pending"
}

### Listar tarefas
GET {{host}}/api/tasks?pageNumber=1&pageSize=10

### Buscar por status
GET {{host}}/api/tasks?status=Pending
